### ISSUE TITLE
The replay operation of xwc_node is too slow

### ISSUE THREAD

**Issue by Whitecoin-Owner** [Whitecoin-Owner/Whitecoin-core#11]
If I force close `QT wallect` and restart it, `xwc_node` will spend a log time(more than 5 hours) to replay the transactions.  It's very sad. Can we improve it?

**Comment by urcoder-9527** [comment]
We can remember the  last replay position,  and  when  replay operation is happened, we will check  the last position. If  it's  valid, we can replay it from last position, otherwise we replay it from position `1`.

**Comment by urcoder-9527** [comment]
If start `xwc_node` with options `--replay or --replay-blockchain`, it will replay all local block, this operation will spend many many time.
During replay local block, `xwc_node` can't do any thing, So we will close it beginning with version `1.2.9`.

**Comment by urcoder-9527** [comment]
The `1.2.9` is released.
