### ISSUE TITLE
Modify the init XWC node list

### ISSUE THREAD

**Issue by Whitecoin-Owner** [Whitecoin-Owner/Whitecoin-core#13]
## AS-IS
Now, we only write 6 xwc nodes to source code, we should improve it.

## TO-BE
Use new 50 xwc_nodes to init defualt node list.

**Comment by urcoder-9527** [comment]
Compile graphene_app at windows platform, we need fix the error `fatal error C1060`
https://blog.csdn.net/huijielic/article/details/100075742

**Comment by urcoder-9527** [comment]
The `v1.2.9` is released.
