### ISSUE TITLE
Rpc response has expire in header 

### ISSUE THREAD

**Issue by helyho** [Whitecoin-Owner/Whitecoin-core#8]
It has conflict with Apache HttpClient, HttpClient will check expire and drop it.

expire in header is declareed by http1.1

can you remove the expire from header? 

thx alot.

**Comment by urcoder-9527** [comment]
@helyho 
I checked & test http response, we don't add `expires` field. can you show me more information? for example:
* http url
* http request

I guess the `expires` field add by proxy, such as nginx.

**Comment by haosj01** [comment]
请求XWC链返回Assert Exception: trx.expiration <= now + chain_parameters.maximum_time_until_expiration:

**Comment by Whitecoin-Owner** [comment]
close this issue now.
